- name: Environment Setup
  hosts: pxe
  remote_user: root

  tasks:
    - name: Install Docker
      apt:
        pkg:
          - docker.io
          - docker-compose

    - name: Install Qemu
      apt:
        pkg:
          - qemu
          - qemu-kvm

    - name: Install Git
      apt:
        pkg:
          - git

    - name: Install Screen
      apt:
        pkg:
          - git


- name: Prepare PXE
  hosts: pxe
  remote_user: root

  tasks:       
     - name: Delete previouse project
       command: rm -rf /opt/dedicated-project/

     - name: Clone Project
       command: git clone https://github.com/DeMysteriisMundi/pxe-project /opt/dedicated-project/
      
     - name: Create VM
       command: ./qemu-vm/qemu-vm.sh create
       args:
         chdir: /opt/dedicated-project/


- name: Start PXE
  hosts: pxe
  remote_user: root

  tasks:
    - name: Start Services
      command: docker-compose up -d
      args:
        chdir: /opt/dedicated-project/
        
    - name: Start VM
      command: ./qemu-vm/qemu-vm.sh start
      async: 7200
      poll: 0
      args:
        chdir: /opt/dedicated-project/

