- name: Environment Setup
  hosts: pxe
  remote_user: root

  tasks:
    - name: Install Docker
      apt:
        pkg:
          - docker.io
          - docker-compose

    - name: Install Git
      apt:
        pkg:
          - git


- name: Prepare PXE
  hosts: pxe
  remote_user: root

  tasks:       
     - name: Delete previouse project
       command: rm -rf /opt/dedicated-project/

     - name: Clone Project
       command: git clone https://github.com/DeMysteriisMundi/pxe-project /opt/dedicated-project/


- name: Start PXE
  hosts: pxe
  remote_user: root

  tasks:
    - name: Start Services
      command: docker-compose up -d
      args:
        chdir: /opt/dedicated-project/

